openapi: "3.0.0"
info:
  version: v1
  title: BFK
  license:
    name: MIT
servers:
  - url: https://data.bufdir.no/v1/bfk
paths:
  '':
    get:
      summary: Returnerer en liste over bfk modellene som er tilgjengelige. Kun de viktigste egenskapene til bfk-modellene blir returnert.
      tags:
        - bfk 
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/BarnevernfagligKvalitetsystem"   
  /{versjon}:
    get:
      summary: Returnerer en komplett bfk-modell
      tags:
        - bfk
      responses:
        '200':
          description: Forventet response på en gyldig rekvest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BarnevernfagligKvalitetssystem"     
components:
  schemas:
    BarnevernfagligKvalitetsystem:
      type: object
      description: Kvalitetssystemet
      required:
        - versjon
        - versjonsInformasjon
      properties:
        versjon:
          type: string
          description: Versjonsnummeret til denne bfk-modellen
        versjonsInformasjon:
          type: string
          description: Beskrivelse av endringene i denne versjonen sett i forhold til forrige versjon
        gjelderFra:
          type: string
          format: date
        gjelderTil:
          type: string
          format: date
        kunnskapsmodell:
          $ref: "#/components/schemas/Kunnskapsmodell" 
        faser:
          type: array
          items:
            $ref: "#/components/schemas/Fase"
        prosesser: 
          type: array
          items:
            $ref: "#/components/schemas/Prosess"
        spørsmål:
          type: array
          items:
            $ref: "#/components/schemas/Spørsmål"
        kunnskap: 
          type: array
          items: 
            $ref: "#/components/schemas/Kunnskap"
        kilder: 
          type: array
          items: 
            $ref: "#/components/schemas/Kilde"
    Kunnskapsmodell:
      type: object
      required:
        - id        
      description: "Beskrivelse av kunnskapsmodell"
      properties:
        id: 
          type: string    
          format: uri
        beskrivelse:
          type: string    
        dimensjoner:
          description: 
          type: array
          items:
            $ref: "#/components/schemas/Dimensjon"
          minItems: 3        
    Dimensjon:
      type: object
      required:
        - id
        - navn
        - definisjon
      properties:
        id:
          type: string
          format: uri
        kode:
          type: string
        navn:
          type: string
        definisjon:
          type: string
          contentMediaType: text/html
        beskrivelse:
          type: string
          contentMediaType: text/html
        områder: 
          type: array
          items: 
            $ref: "#/components/schemas/Område"          
    Område:
      type: object
      required:
        - id
        - navn
        - definisjon
      properties:
        id: 
          type: string
          format: uri
        kode:
          type: string
        navn: 
          type: string
        definisjon:
          type: string
          contentMediaType: text/html
        beskrivelse:
          type: string
          contentMediaType: text/html
        kunnskap:
          type: array
          items: 
            type: string
            format: uri-reference
        spørsmål: 
          type: array
          items: 
            type: string
            format: uri-reference       
    Spørsmål:
      type: object
      properties:
        id:
          type: string
          format: uri
        type:
          type: string
          enum: ["reflekterende", "generelt"]
        spørsmålstekst:
          type: string
          contentMediaType: text/html
        dimensjoner:
          type: array
          items: 
            type: string
            format: uri-reference 
        områder:
          type: array
          items: 
            type: string
            format: uri-reference 
        oppgaver:
          type: array
          items: 
            type: string
            format: uri-reference                 
    Fase:
      type: object
      required: 
        - id
      properties:
        id: 
          type: string
          format: uri
        navn:
          type: string
        definisjon:
          type: string
          contentMediaType: text/html
        regler:
          type: string
          description: Oppsummering av reglene som gjelder for denne fasen
        frist:
          type: integer
          description: Maksimumskrav til antall kalenderdager fasen kan vare
        kunnskap:
          type: array
          items: 
            type: string
            format: uri-reference
        kilder: 
          type: array
          items:
            $ref: "#/components/schemas/Kildeforhold"
          description: Liste av kildehenvisninger
    Prosess:
      type: object
      required:
        - id
        - navn
        - definisjon
      properties:
        id:
          type: string
          format: uri
        navn:
          type: string
        definisjon:
          type: string
          contentMediaType: text/html
        fase:
          type: string
          format: uri-reference
          description: Prosessens tilhørerende fase
        kunnskap:
          type: array
          items: 
            type: string
            format: uri-reference
        kilder: 
          type: array
          items:
            $ref: "#/components/schemas/Kildeforhold"
          description: Liste av kildehenvisninger   
        oppgaver:
          type: array
          items:
            $ref: "#/components/schemas/Oppgave"
    Oppgave:
      type: object
      required:
        - id
        - navn
        - definisjon
      properties:
        id: 
          type: string
          format: uri
        navn:
          type: string
        definisjon:
          type: string
          contentMediaType: text/html
        kunnskap:
          type: array
          items: 
            type: string
            format: uri-reference
        kunnskapsmodell:
          type: string
          format: uri-reference
        sjekkliste:
          type: array
          items:
            $ref: "#/components/schemas/SjekklisteElement"
        spørsmål:
          type: array
          items:
            $ref: "#/components/schemas/spørsmål"
        kilder: 
          type: array
          items:
            $ref: "#/components/schemas/Kildeforhold"
          description: Liste av kildehenvisninger          
        aktiviteter: 
          type: array
          items: 
            $ref: "#/components/schemas/Aktivitet"
    Aktivitet:
      type: object
      required:
        - navn
      properties:
        navn:
          type: string
        definisjon: 
          type: string
          contentMediaType: text/html     
    Kunnskap:
      type: object
      required:
        - tittel
        - tekstType
        - tekst
      properties:
        id: 
          type: string
          format: uri
        tittel:
          type: string
        type:
          type: string
          enum: ["introtekst", "hjelpetekst", "fordypningstekst"]
        artikkel:
          type: string
          description: Sammenfatning av kunnskapen
          contentMediaType: text/html
        emneord:
          type: array
          items: 
            type: string
            format: uri-reference
          description: Referanse til begrepskatalogen
        kilder: 
          type: array
          items:
            $ref: "#/components/schemas/Kildeforhold"
          description: Liste av kildehenvisninger
    SjekklisteElement:
      type: object
      properties:
        tittel:
          type: string
        beskrivelse: 
          type: string
          contentMediaType: "text/html"
    Kildeforhold:
      type: object
      properties:
        forhold:
          type: string
          enum: ["gjengitt", "referert til", "lenket til", "sitert fra", "bygget på", "konkludert ut fra", "anbefalt av", "teori brukt", "perspektivet til"]
        kilde: 
          type: string
          format: uri-reference          
    Kilde:
      type: object
      description: En kildehenvisning
      required:
       - id
      properties:
        id: 
          type: string
          format: uri
        tittel: 
          type: string
        forfatter:
          type: string
        utgiver: 
          type: string
        url:
          type: string
          format: uri-reference
        år:
          type: integer      
          description: Utgivelsesår
        type:
          type: string
          enum: [ "lovverk", "forskrift", "forskning", "veileder", "metode" ]
        opprettet: 
          type: string
          format: date  
          description: Dato for når kilden ble opprettet
    Error:
      type: object
      required:
        - kode
        - meldig
      properties:
        kode:
          type: integer
          format: int32
        melding:
          type: string
