openapi: "3.0.0"
info:
  version: v1
  title: BFK
  license:
    name: MIT
servers:
  - url: https://data.bufdir.no/v1/bfk
paths:
  '':
    get:
      summary: Returnerer en liste over bfk modellene som er tilgjengelige. Kun de viktigste egenskapene til bfk-modellene blir returnert.
      tags:
        - bfk 
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/BarnevernfagligKvalitetsystem"   
  /{versjon}:
    get:
      summary: Returnerer en komplett bfk-modell
      tags:
        - bfk
      responses:
        '200':
          description: Forventet response på en gyldig rekvest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BarnevernfagligKvalitetssystem"
  /{versjon}/prosesser/{prosessId}:
    get:
      summary: hent en spesifik prosess
      tags:
        - prosess      
components:
  schemas:
    BarnevernfagligKvalitetsystem:
      type: object
      description: Kvalitetssystemet
      required:
        - versjon
        - versjonsInformasjon
      properties:
        versjon:
          type: string
          description: Versjonsnummeret til denne bfk-modellen
        versjonsInformasjon:
          type: string
          description: Beskrivelse av endringene i denne versjonen sett i forhold til forrige versjon
        gyldigFra:
          type: string
          format: date
        gyldigTil:
          type: string
          format: date
        kunnskapsmodell:
          type:
            $ref: "#/components/schemas/Kunnskapsmodell" 
        faser:
          type: array
          items:
            $ref: "#/components/schemas/Fase"
        prosesser: 
          type: array
          items:
            $ref: "#/components/schemas/Prosess"
        spørsmål:
          type: array
          items:
            $ref: "#/components/schemas/Spørsmål"
        kunnskap: 
          type: array
          items: 
            $ref: "#/components/schemas/Kunnskap"
        kilder: 
          type: array
          items: 
            $ref: "#/components/schemas/Kilde"
    Kunnskapsmodell:
      type: object
      description: "Beskrivelse av kunnskapsmodell"
      properties:
        id: 
          type: string    
          format: uri
        beskrivelse:
          type: string    
        dimensjoner:
          description: 
          type: array
          items:
            $ref: "#/components/schemas/Dimensjon"
          minItems: 3        
    Dimensjon:
      type: object
      required:
        - id
        - navn
        - definisjon
      properties:
        id:
          type: string
          format: uri
        kode:
          type: string
        navn:
          type: string
        definisjon:
          type: string
        beskrivelse:
          type: string
        områder: 
          type: array
          items: 
            $ref: "#/components/schemas/Område"          
    Område:
      type: object
      required:
        - id
        - navn
        - definisjon
      properties:
        id: 
          type: string
          format: uri
        kode:
          type: string
        navn: 
          type: string
        definisjon:
          type: string
        beskrivelse:
          type: string
    Spørsmål:
      type: object
      properties:
        id:
          type: string
          format: uri
        type:
          type: string
          enum: ["reflekterende", "generelt"]
        spørsmålstekst:
          type: string
        områdeReferanse:
          type: array
          items: 
            type: string
            format: uri-reference     
    Fase:
      type: object
      required: 
        - id
      properties:
        id: 
          type: string
          format: uri
        navn:
          type: string
        definisjon:
          type: string
        frist:
          type: integer
          description: Maksimumskrav til antall kalenderdager fasen kan vare
    Prosess:
      type: object
      required:
        - id
        - navn
        - definisjon
      properties:
        id:
          type: string
          format: uri
        navn:
          type: string
        definisjon:
          type: string
        fase:
          type: string
          format: uri-reference          
        oppgaver:
          type: array
          items:
            $ref: "#/components/schemas/Oppgave"
    Oppgave:
      type: object
      required:
        - id
        - navn
        - definisjon
      properties:
        id: 
          type: string
          format: uri
        navn:
          type: string
        definisjon:
          type: string
        tiltak: 
          type: array 
          items:
            $ref: "#/components/schemas/TiltakType"
        aktiviteter: 
          type: array
          items: 
            $ref: "#/components/schemas/Aktivitet"
    Aktivitet:
      type: object
      required:
        - navn
      properties:
        id: 
          type: string 
          format: uri
        navn:
          type: string
        definisjon: 
          type: string          
    Kunnskap:
      type: object
      required:
        - tittel
        - TekstType
        - tekst
      properties:
        id: 
          type: string
          format: uri
        tittel:
          type: string
        type:
          $ref: "#/components/schemas/TekstType"
        tekst:
          type: string
          description: Sammenfatning av kunnskapen
        emneord:
          description: Referanse til begrepskatalogen
          type: array
          items: 
            type: string
            format: uri-reference
        kilde: 
          description: Liste av kildehenvisninger
          type: array
          items:
            $ref: "#/components/schemas/Kilde"
    Kilde:
      type: object
      description: En kildehenvisning
      properties:
        referanse: 
          type: string
          format: uri-reference
        autoritet:
          type: string
          description: Angivelse av hvilken autoritet som kilden har
          example: Norsk lov
        dato: 
          type: string
          format: date  
          description: Dato for når kilden ble referert
    TekstType:
      type: string
      enum: ["introtekst", "hjelpetekst", "fordypningstekst"]
    FaseType:
      type: string
      enum: ["bekymringsmelding", "undersøkelse", "tiltak", "evaluering"]
    TiltakType:
      type: string
      enum: ["akutt", "fosterhjemsplassering", "institusjonsplassering"]
    Error:
      type: object
      required:
        - kode
        - meldig
      properties:
        kode:
          type: integer
          format: int32
        melding:
          type: string